[env:btt_octopus_f446]
platform = ststm32
board = btt_octopus
framework = arduino
board_build.variants_dir = custom_variants
upload_protocol = stlink
debug_tool = stlink

lib_deps =
    waspinator/AccelStepper@^1.64

build_flags =
    -D HSE_VALUE=12000000U
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D HAL_QSPI_MODULE_DISABLED